# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug64
endif
export config

PROJECTS := shader_kit Robot

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

shader_kit: 
	@echo "==== Building shader_kit ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f shader_kit.make

Robot: 
	@echo "==== Building Robot ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f Robot.make

clean:
	@${MAKE} --no-print-directory -C . -f shader_kit.make clean
	@${MAKE} --no-print-directory -C . -f Robot.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug64"
	@echo "   release64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   shader_kit"
	@echo "   Robot"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
